version: '3.7'

services:
  nginx-server:
    restart: always
    container_name: 'nginx-server'
    image: 'hermanvfx/nginx:latest'
    depends_on:
      - front_app
    ports:
      - '80:80'

  front_app:
    container_name: 'project-avito4_1_front'
    image: 'hermanvfx/avito4_1_front:latest'
  #    ports:
  #      - '3000:3000'
  mysql:
    container_name: 'mysql-image'
    image: 'hermanvfx/mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=platform'
    healthcheck:
      test: "mysql -uroot -proot platform -e 'select 1'"
      interval: 1s
      retries: 120
    cap_add:
      - SYS_NICE

  app:
    container_name: 'project-avito4_1_back'
    image: 'hermanvfx/avito4_1_app:latest'
    ports:
      - '8888:8888'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-image:3306/platform?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
